/**********************************************************************************************************************
 * \file ADC_Scan.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxVadc_Adc.h"

#include "ADC_Scan.h"

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
static IfxVadc_Adc         g_vadc;                                 // VADC 모듈 설정
static IfxVadc_Adc_Group   g_vadcGroup;                            // VADC 그룹 설정
static IfxVadc_Adc_Channel g_vadcChannel;                          // VADC 채널 설정
static IfxVadc_ChannelId   g_vadcChannelID = IfxVadc_ChannelId_7;  // AN39: channel 7 of group 4

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
static void initVADCModule(void);
static void initVADCGroup(void);
static void initVADCChannel(void);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
// Versatile Analog-to-Digital Converter (VADC)
void initADC(void)
{
    initVADCModule();
    initVADCGroup();
    initVADCChannel();

    IfxVadc_Adc_startScan(&g_vadcGroup);  // 설정된 그룹에서 스캔 시작
}

// ADC 값을 읽어 오는 함수
uint16 readADCValue(void)
{
    Ifx_VADC_RES conversionResult;
    do
    {
        conversionResult = IfxVadc_Adc_getResult(&g_vadcChannel);
    } while (!conversionResult.B.VF);

    return conversionResult.B.RESULT;
}

static void initVADCModule(void)
{
    // 설정 초기화
    IfxVadc_Adc_Config adcConfig;
    IfxVadc_Adc_initModuleConfig(&adcConfig, &MODULE_VADC);

    // 모듈 초기화
    IfxVadc_Adc_initModule(&g_vadc, &adcConfig);
}

static void initVADCGroup(void)
{
    // 설정 초기화
    IfxVadc_Adc_GroupConfig adcGroupConfig;
    IfxVadc_Adc_initGroupConfig(&adcGroupConfig, &g_vadc);

    // 그룹 설정
    adcGroupConfig.groupId = IfxVadc_GroupId_4;
    adcGroupConfig.master  = adcGroupConfig.groupId;

    adcGroupConfig.arbiter.requestSlotScanEnabled       = TRUE;                       // 요청 소스 설정
    adcGroupConfig.scanRequest.autoscanEnabled          = TRUE;                       // 자동 스캔 활성화
    adcGroupConfig.scanRequest.triggerConfig.gatingMode = IfxVadc_GatingMode_always;  // 게이팅 모드 설정

    // 그룹 초기화
    IfxVadc_Adc_initGroup(&g_vadcGroup, &adcGroupConfig);
}

static void initVADCChannel(void)
{
    // 설정 초기화
    IfxVadc_Adc_ChannelConfig adcChannelConfig;
    IfxVadc_Adc_initChannelConfig(&adcChannelConfig, &g_vadcGroup);

    // 채널 설정
    adcChannelConfig.channelId      = g_vadcChannelID;
    adcChannelConfig.resultRegister = (IfxVadc_ChannelResult)g_vadcChannelID;

    // 채널 초기화
    IfxVadc_Adc_initChannel(&g_vadcChannel, &adcChannelConfig);

    // 채널 스캔 여부 설정
    uint32 channels = 1 << adcChannelConfig.channelId;
    uint32 mask     = channels;
    IfxVadc_Adc_setScan(&g_vadcGroup, channels, mask);
}
