/**********************************************************************************************************************
 * \file GTM_TOM_PWM.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxGtm_Tom_Pwm.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ISR_PRIORITY_TOM 20     // 인터럽트 우선순위
#define PWM_PERIOD       50000  // PWM 주기 (tick)

#define LED1 IfxGtm_TOM0_2_TOUT104_P10_2_OUT  // Digital pin 13 - P10.2

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
static IfxGtm_Tom_Pwm_Config g_tomConfig;  // TOM 설정
static IfxGtm_Tom_Pwm_Driver g_tomDriver;  // TOM 드라이버

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
static void setDutyCycle(uint16 dutyCycle);

/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/
// Timer Output Module (TOM)
void initGtmTomPwm(void)
{
    // GTM 활성화
    IfxGtm_enable(&MODULE_GTM);

    // FXU 클럭 활성화
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_FXCLK);

    // 설정 초기화
    IfxGtm_Tom_Pwm_initConfig(&g_tomConfig, &MODULE_GTM);

    g_tomConfig.tom                      = LED1.tom;      // 모듈 설정
    g_tomConfig.tomChannel               = LED1.channel;  // 채널 설정
    g_tomConfig.period                   = PWM_PERIOD;    // 주기 설정
    g_tomConfig.pin.outputPin            = &LED1;         // 출력 핀 설정
    g_tomConfig.synchronousUpdateEnabled = TRUE;          // 업데이트 메커니즘 설정

    // TOM 초기화 및 PWM 시작
    IfxGtm_Tom_Pwm_init(&g_tomDriver, &g_tomConfig);
    IfxGtm_Tom_Pwm_start(&g_tomDriver, TRUE);
}

// LED 밝기를 제어하는 함수
void controlLED(float32 brightness)
{
    // brightness는 [0, 1] 범위의 실수 값
    setDutyCycle(brightness * PWM_PERIOD);
}

static void setDutyCycle(uint16 dutyCycle)
{
    // 듀티 사이클 설정
    g_tomConfig.dutyCycle = dutyCycle;

    // TOM 초기화
    IfxGtm_Tom_Pwm_init(&g_tomDriver, &g_tomConfig);
}
