/**********************************************************************************************************************
 * \file STM_Interrupt.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Bsp.h"

#include "Task_Scheduler.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ISR_PRIORITY_STM 40  // 인터럽트 우선순위
#define TIMER_INT_TIME   1   // 인터럽트 주기 (ms)

#define STM0 &MODULE_STM0  // STM for CPU0

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
static IfxStm_CompareConfig g_STMConf;      // STM 설정
static uint32               g_ticksFor1ms;  // 1ms에 해당하는 틱 수

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
// 벡터 테이블에 ISR 등록
IFX_INTERRUPT(isrSTM, 0, ISR_PRIORITY_STM);

// Interrupt Service Routine (ISR)
void isrSTM(void)
{
    // 다음 인터럽트를 트리거할 틱 값으로 CMP 레지스터 업데이트
    IfxStm_increaseCompare(STM0, g_STMConf.comparator, g_ticksFor1ms);

    g_counter1ms++;
    g_taskFlags.isTask1msReady = TRUE;

    // 카운터 값에 따라 작업 플래그 설정
    if (g_counter1ms % 10 == 0)
    {
        g_taskFlags.isTask10msReady = TRUE;
    }

    if (g_counter1ms % 100 == 0)
    {
        g_taskFlags.isTask100msReady = TRUE;
    }

    if (g_counter1ms % 1000 == 0)
    {
        g_taskFlags.isTask1000msReady = TRUE;
    }
}

// System Timer (STM)
void initSTM(void)
{
    // 시간을 틱으로 변환
    g_ticksFor1ms = IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, TIMER_INT_TIME);

    // 설정 초기화
    IfxStm_initCompareConfig(&g_STMConf);

    g_STMConf.triggerPriority = ISR_PRIORITY_STM;  // 인터럽트 우선순위 설정
    g_STMConf.typeOfService   = IfxSrc_Tos_cpu0;   // 인터럽트 서비스 제공자 설정
    g_STMConf.ticks           = g_ticksFor1ms;     // 첫 번째 인터럽트를 트리거할 틱 값 설정

    // STM 초기화
    IfxStm_initCompare(STM0, &g_STMConf);
}
