/**********************************************************************************************************************
 * \file GPIO_LED_Button.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef GPIO_LED_BUTTON_H_
#define GPIO_LED_BUTTON_H_

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
// GPIO 핀의 입/출력 모드 정의
typedef enum
{
    MyPort_Mode_inputNoPullDevice      = 0x00U,  // Input, No pull device connected
    MyPort_Mode_inputPullDown          = 0x01U,  // Input, pull-down device connected
    MyPort_Mode_inputPullUp            = 0x02U,  // Input, pull-up device connected
    MyPort_Mode_outputPushPullGeneral  = 0x10U,  // Push-pull, General-purpose output
    MyPort_Mode_outputPushPullAlt1     = 0x11U,  // Push-pull, Alternate output function 1
    MyPort_Mode_outputPushPullAlt2     = 0x12U,  // Push-pull, Alternate output function 2
    MyPort_Mode_outputPushPullAlt3     = 0x13U,  // Push-pull, Alternate output function 3
    MyPort_Mode_outputPushPullAlt4     = 0x14U,  // Push-pull, Alternate output function 4
    MyPort_Mode_outputPushPullAlt5     = 0x15U,  // Push-pull, Alternate output function 5
    MyPort_Mode_outputPushPullAlt6     = 0x16U,  // Push-pull, Alternate output function 6
    MyPort_Mode_outputPushPullAlt7     = 0x17U,  // Push-pull, Alternate output function 7
    MyPort_Mode_outputOpenDrainGeneral = 0x18U,  // Open-drain, General-purpose output
    MyPort_Mode_outputOpenDrainAlt1    = 0x19U,  // Open-drain, Alternate output function 1
    MyPort_Mode_outputOpenDrainAlt2    = 0x1AU,  // Open-drain, Alternate output function 2
    MyPort_Mode_outputOpenDrainAlt3    = 0x1BU,  // Open-drain, Alternate output function 3
    MyPort_Mode_outputOpenDrainAlt4    = 0x1CU,  // Open-drain, Alternate output function 4
    MyPort_Mode_outputOpenDrainAlt5    = 0x1DU,  // Open-drain, Alternate output function 5
    MyPort_Mode_outputOpenDrainAlt6    = 0x1EU,  // Open-drain, Alternate output function 6
    MyPort_Mode_outputOpenDrainAlt7    = 0x1FU   // Open-drain, Alternate output function 7
} MyPort_Mode;

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void initGPIO(void);
void controlLED(void);

#endif /* GPIO_LED_BUTTON_H_ */
